blank_issues_enabled: true
contact_links:
  - name: 💬 General Questions about Bait
    url: https://github.com/bait-lang/bait/discussions/categories/questions-and-answers
    about: Ask or answer questions in the discussions section.
  - name: Join the Discord Community
    url: https://discord.gg/sM8mspGMnf
    about: Chat about everything related to Bait.
