name: CI

on:
  pull_request:
  push:

jobs:
  linux-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - name: Bootstrap (single pass)
        run: ./make.sh --no-self
      - name: Bootstrap
        run: |
          ./make.sh
          ./bait symlink
      - name: Build tools
        run: bait build-tools
      - name: Build examples
        run: bait build-examples -b js
      - name: Run compiler tests
        run: bait test tests
      - name: Run lib tests
        run: bait test lib
      - name: Run tool tests
        run: bait test cli/tools
      - name: Check markdown code blocks
        run: |
          bait check-md docs/docs.md
          bait check-md README.md

  linux-c:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      # Note: this job still uses bait.js
      - name: Bootstrap
        run: |
          ./make.sh
          ./bait symlink
      # - name: Build tools
      #   run: bait build-tools -b c

      - name: Build examples
        run: bait build-examples -b c
      - name: Run compiler tests
        run: |
          bait test -b c tests/array
          bait test -b c tests/auto_str
          bait test -b c tests/for/loop_test.bt
          bait test -b c tests/for/for_in_test.bt
          bait test -b c tests/int/promotion_test.bt
          # bait test -b c tests/int/bitwise_test.bt
      - name: Run lib tests
        run: |
          # bait test -b c lib/bait
          bait test -b c lib/builtin
          # bait test -b c lib/cli
          bait test -b c lib/encoding
          bait test -b c lib/hash
          bait test -b c lib/os
          bait test -b c lib/strings
      # - name: Run tool tests
        # run: bait test cli/tools
      # - name: Check markdown code blocks
      #   run: |
      #     bait check-md docs/docs.md
      #     bait check-md README.md

  windows-js:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - name: Bootstrap
        run: |
          ./make.bat
          ./bait.bat symlink --ghci-win
      - name: Build tools
        run: bait build-tools
      - name: Build examples
        run: bait build-examples
      - name: Run compiler tests
        run: bait test tests
      - name: Run lib tests
        run: bait test lib
      - name: Run tool tests
        run: bait test cli/tools
      - name: Check markdown code blocks
        run: |
          bait check-md docs/docs.md
          bait check-md README.md
